name: Grocery Produce API CI Pipeline

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # run on ubuntu
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      # installs dependencies, builds and runs tests
      - name: Build project and run tests
        run: |
          go get -d -v ./... && go install -v ./...
          go build
          go test -v ./tests/

      - name: Build Docker Container
        run: |
          docker build -f Dockerfile -t grocery-store-api .
          
      # push to the docker hub repo
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: murphylsou/grocery-store-api
          tag_with_ref: true
